name: Pro-Wyscout-Femenino-Engine

on:
  workflow_dispatch:

jobs:
  scrape_and_analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install scrapling supabase requests curl-cffi patchright playwright msgspec lxml browserforge python-dotenv
          python -m playwright install chromium
          python -m playwright install-deps chromium

      - name: Run Orchestrator
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python main_orchestrator.py

      # ESTA ES LA SECCIÓN QUE TE FALTA Y QUE CREA EL BOTÓN DE DESCARGA
      - name: Generar botón de descarga de datos
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: datos_extraidos_solares # Nombre del paquete
          path: resultados_seguridad.json # El archivo que crearemos en Python
